### ISSUE TITLE
`.define` seems dangerous

### ISSUE THREAD

**Issue by wavebeem** [sgentle/catenary#3]
Given that `.define` adds a function to the entire catenary library, it's basically like adding a global to your program. Say you include libraries `foo` and `bar` which both include catenary and both `.define` something called `print`, one would get clobbered.

I understand the chaining syntax is nice, but this seems like it would hinder library adoption in the future. Given that you can insert a function simply using `.cat(f)`, this feature seems unwise.

**Comment by sgentle** [comment]
Yeah, that's a good point. I'm a little conflicted on this because it's nice to have the ability to define stuff that applies across all your libraries, but it also a bit of a footgun to have that be the default.

`cat.instance` creates a new local instance so definitions only apply within that scope. You won't have any problems if you always do this: `cat = require('catenary').instance`, but you do need to rely on everyone following that convention. I'd consider making that the default but because of node's [module caching](https://nodejs.org/api/modules.html#modules_caching) `require('catenary')` will usually give you a shared object, so there'd always be some extra step required to get a local instance.

As for definitions in general, I think they have to stay. Definitions are a pretty fundamental part of the concatenative style. [Quoth Chuck Moore](http://www.ultratechnology.com/1xforth.htm): "Forth is highly factored code. I don't know anything else to say except that Forth is definitions. If you have a lot of small definitions you are writing Forth."

I would say that it's bad form for libraries to `.define` things themselves. Instead they should export an object that can be `.import`ed, as is the case with the standard library (see `lib/string.coffee` etc)

What do you think?

**Comment by wavebeem** [comment]
Right, so users would need some kind of per-module wrapper like so:

``` javascript
/// cat-wrapper.js
module.exports = require('catenary').instance
```

You could always make `catenary` export nothing useful by default, except a function that returns a new instance. That way no one can patch `catenary` in a way others can see, forcing them into the `cat-wrapper` style.

Sort of an annoying step, but it should completely remove the accidental stomping scenario.

> I would say that it's bad form for libraries to .define things themselves. Instead they should export an object that can be .imported, as is the case with the standard library (see lib/string.coffee etc)

Agreed, but just thinking about making this resilient against carelessness.

**Comment by sgentle** [comment]
> You could always make catenary export nothing useful by default, except a function that returns a new instance.

Yes, good thinking. My only concern is that I can see some uses for being able to clobber the namespace (eg, sharing definitions between files in your own code) and I don't have enough information on actual use of the library yet to know how to make the tradeoff. Your solution seems like the best way forward if it turns into a problem.

I'm going to close this for now with the intention of going back to it later when (and if!) Catenary gets big enough to revisit the decision with real usage information.
