### ISSUE TITLE
Higher order functions do not work

### ISSUE THREAD

**Issue by wavebeem** [sgentle/catenary#4]
It seems the library scans the stack from left to right, attempting to evaluate functions as soon as they are seen, with arguments grabbed from the left according to the `.length` of the function in question.

Due to this, higher order functions, such as `map`, do not appear to be supported.

``` javascript
var cat = require('catenary')

var xs = [1, 2, 3]
var negate = function(x) { return -x }
var map = function(f, xs) { return xs.map(f) }
var print = function(x) { console.log(x) }

cat(negate, xs, map, print)()
```

Suggestion: Provide a way to wrap functions so the evaluator will skip them as "data" and keep scanning for functions. Or assume functions are data by default and use a different method besides `cat` to insert functions that are meant to be used.

Yields the error:

```
Error: Not enough items on the stack! (needed 1, had 0)
  at Function.proto._assertLength (/Users/brian/OneDrive/Code/misc/catenary-playground/node_modules/catenary/catenary.coffee.md:47:13)
  at Function.exec (/Users/brian/OneDrive/Code/misc/catenary-playground/node_modules/catenary/catenary.coffee.md:142:9)
  at Function.proto._execute (/Users/brian/OneDrive/Code/misc/catenary-playground/node_modules/catenary/catenary.coffee.md:115:20)
  at cat (/Users/brian/OneDrive/Code/misc/catenary-playground/node_modules/catenary/catenary.coffee.md:67:20)
  at Object.<anonymous> (/Users/brian/OneDrive/Code/misc/catenary-playground/main.js:8:28)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by wavebeem** [comment]
On second look, it seems I didn't notice the section on higher order programming.

I think this is probably safe to close.

**Comment by sgentle** [comment]
You should be able to do this by wrapping functions to be evaluated in another cat:

``` javascript
cat(cat(negate), xs, map, print)()
```

However the issue with that is your `map` function doesn't then know how to receive a cat as input. One solution is to change it to do this:

``` javascript
var map = function(f, xs) { return xs.map(f.$) }
```

But I think you may find it easier to use the standard library's `map`

``` javascript
cat(xs, cat(negate)).map.print()
```

Or since `neg` is also in the standard library:

``` javascript
cat(xs, cat.neg).map.print()
```

**Comment by wavebeem** [comment]
Ah, I wasn't aware of the wealth of functions built-in. I was able to fix my map as follows:

``` javascript
var xs = [1, 2, 3]
var Negate = function(x) { return -x }
var Map = function(f, xs) { return xs.map(function(x) { return f.$(x) }) }
var Print = function(x) { console.log(x) }

cat.define('Map', Map)
cat.define('Negate', Negate)
cat.define('Print', Print)

cat(cat.Negate, xs).Map.Print()
```

It might be worth mentioning that if you integrate your own higher-order functions into catenary that you'll need to use `.$` to avoid getting another catenary instance back out. I was very confused as to what I was seeing.

It does seem unfortunate to me that the defined function needs to know how to take the func arg out of its cat instance, but I don't really know how else this could be solved.

**Comment by sgentle** [comment]
Right, yeah. I think the problem is that it's pretty difficult for Catenary functions to behave exactly like plain Javascript functions. I messed around with that idea early on in Catenary's development, but the problem is how do you know if you should return just a single value (which would fix this issue) or a cat (which allows you to chain and pass cats into other cats, and do all sorts of important higher-order stuff) 

It's also worth noting that your version of the map function is only able to handle cats of a single function, so `cat(cat.Negate.Negate, xs).Map.Print()` would not work as expected. To fix that you could use `function(x) { return f(x).$ }` instead.

However, even then your map wouldn't work if the cat being passed in required values earlier on the stack, like so:

``` javascript
cat(10, [1,2,3], cat.dupd.times).map.print()
```

You also need to handle pushing multiple values back onto the stack. It should cover every case if you have something like:

``` javascript
var Map = function(f, xs) { var c = this; return c.cat(xs.map(function(x) { return (c=c.cat(x, f).exec()).$ })); }

cat(10, cat.dupd.times, [1,2,3], Map).print()
```

I would probably suggest just using the inbuilt map for that reason. :D
